// also see manual data entered for node placement and handle placemenet in biome-graph.tsx
export const biomes = [
  "Abyss",
  "Ancient Ruins",
  "Badlands",
  "Beach",
  "Cave",
  "Construction Site",
  "Desert",
  "Dojo",
  "Factory",
  "Fairy Cave",
  "Forest",
  "Grassy Field",
  "Graveyard",
  "Ice Cave",
  "Island",
  "Jungle",
  "Laboratory",
  "Lake",
  "Meadow",
  "Metropolis",
  "Mountain",
  "Plains",
  "Power Plant",
  "Sea",
  "Seabed",
  "Slum",
  "Snowy Forest",
  "Space",
  "Swamp",
  "Tall Grass",
  "Temple",
  "Town",
  "Volcano",
  "Wasteland",
]

export const adjacencyList: { [key: string]: [string, number][] } = {
  "Abyss": [["Space", 0.5], ["Cave", 1.0], ["Wasteland", 0.5]],
  "Ancient Ruins": [["Mountain", 1.0], ["Forest", 0.5]],
  "Badlands": [["Mountain", 1.0], ["Desert", 1.0]],
  "Beach": [["Sea", 1.0], ["Island", 0.5]],
  "Cave": [["Lake", 1.0], ["Laboratory", 0.5], ["Badlands", 1.0]],
  "Construction Site": [["Dojo", 0.5], ["Power Plant", 1.0]],
  "Desert": [["Ancient Ruins", 1.0], ["Construction Site", 0.5]],
  "Dojo": [["Plains", 1.0], ["Jungle", 0.5], ["Temple", 0.5]],
  "Factory": [["Plains", 1.0], ["Laboratory", 0.5]],
  "Fairy Cave": [["Space", 0.5], ["Ice Cave", 1.0]],
  "Forest": [["Meadow", 1.0], ["Jungle", 1.0]],
  "Grassy Field": [["Tall Grass", 1.0]],
  "Graveyard": [["Abyss", 1.0]],
  "Ice Cave": [["Snowy Forest", 1.0]],
  "Island": [["Sea", 1.0]],
  "Jungle": [["Temple", 1.0]],
  "Laboratory": [["Construction Site", 1.0]],
  "Lake": [["Swamp", 1.0], ["Beach", 1.0], ["Construction Site", 1.0]],
  "Meadow": [["Plains", 1.0], ["Fairy Cave", 1.0]],
  "Metropolis": [["Slum", 1.0]],
  "Mountain": [["Space", 0.33], ["Volcano", 1.0], ["Wasteland", 0.5]],
  "Plains": [["Grassy Field", 1.0], ["Metropolis", 1.0], ["Lake", 1.0]],
  "Power Plant": [["Factory", 1.0]],
  "Sea": [["Seabed", 1.0], ["Ice Cave", 1.0]],
  "Seabed": [["Cave", 1], ["Volcano", 0.33]],
  "Slum": [["Construction Site", 1.0], ["Swamp", 0.5]],
  "Snowy Forest": [["Forest", 1.0], ["Mountain", 0.5], ["Lake", 0.5]],
  "Space": [["Ancient Ruins", 1.0]],
  "Swamp": [["Graveyard", 1.0], ["Tall Grass", 1.0]],
  "Tall Grass": [["Cave", 1.0], ["Forest", 1.0]],
  "Temple": [["Desert", 1.0], ["Ancient Ruins", 0.5], ["Swamp", 0.5]],
  "Town": [["Plains", 1.0]],
  "Volcano": [["Beach", 1.0], ["Ice Cave", 0.33]],
  "Wasteland": [["Badlands", 1.0]]
};

// biome -> rarity -> pokemon list
export const pokemonPerBiome: { [key: string]: { [key: string]: string[] } } = {
  "Abyss": {
    "Common": ["Zubat", "Paras", "Misdreavus", "Sableye", "Woobat", "Impidimp"],
    "Uncommon": ["Gastly", "Dunsparce", "Houndour", "Whismur", "Mawile"],
    "Rare": ["Absol", "Spiritomb", "Froslass", "Zorua"],
    "Super Rare": ["Umbreon", "Deino", "Dreepy"],
    "Ultra Rare": ["Darkrai", "Galarian Moltres"],
    "Boss": ["Gengar", "Crobat", "Houndoom", "Sableye", "Froslass", "Zoroark", "Grimmsnarl"],
    "Boss Rare": ["Umbreon", "Spiritomb", "Hydreigon", "Dragapult"],
    "Boss Super Rare": ["Darkrai", "Galarian Moltres"],
    "Boss Ultra Rare": ["Palkia", "Yveltal"],
  },
  "Ancient Ruins": {
    "Common": ["Drowzee", "Natu", "Unown", "Spoink", "Baltoy", "Elgyem"],
    "Uncommon": ["Abra", "Sigilyph", "Tinkatink"],
    "Rare": ["Mr. Mime", "Wobbuffet", "Gothita", "Stonjourner"],
    "Super Rare": ["Espeon", "Archen", "Galarian Yamask"],
    "Ultra Rare": ["Registeel", "Fezandipiti"],
    "Boss": ["Alakazam", "Hypno", "Xatu", "Grumpig", "Claydol", "Sigilyph", "Gothitelle", "Beheeyem", "Tinkaton"],
    "Boss Rare": ["Mr. Mime", "Espeon", "Wobbuffet", "Archeops", "Runerigus"],
    "Boss Super Rare": ["Registeel", "Fezandipiti"],
    "Boss Ultra Rare": ["Koraidon"],
  },
  "Badlands": {
    "Common": ["Diglett", "Geodude", "Cubone", "Rhyhorn", "Phanpy", "Drilbur", "Mudbray"],
    "Uncommon": ["Sandshrew", "Numel", "Roggenrola", "Sizzlipede", "Cufant", "Capsakid"],
    "Rare": ["Onix", "Gligar", "Klawf", "Poltchageist"],
    "Ultra Rare": ["Landorus", "Okidogi"],
    "Boss": ["Dugtrio", "Golem", "Marowak", "Donphan", "Rhyperior", "Gliscor", "Excadrill", "Mudsdale", "Centiskorch", "Copperajah", "Scovillain"],
    "Boss Rare": ["Steelix", "Sinistcha"],
    "Boss Super Rare": ["Landorus", "Okidogi"],
    "Boss Ultra Rare": ["Groudon"],
  },
  "Beach": {
    "Common": ["Shellder", "Krabby", "Staryu", "Corphish", "Dwebble", "Binacle", "Mareanie", "Wiglett"],
    "Uncommon": ["Burmy", "Clauncher", "Sandygast"],
    "Rare": ["Quaxly", "Tatsugiri"],
    "Super Rare": ["Tirtouga"],
    "Ultra Rare": ["Keldeo", "Tapu Fini", "Cresselia"],
    "Boss": ["Cloyster", "Kingler", "Starmie", "Crawdaunt", "Wormadam", "Crustle", "Barbaracle", "Clawitzer", "Toxapex", "Palossand"],
    "Boss Rare": ["Carracosta", "Quaquaval"],
    "Boss Super Rare": ["Keldeo", "Tapu Fini", "Cresselia"]
  },
  "Cave": {
    "Common": ["Zubat", "Paras", "Teddiursa", "Whismur", "Roggenrola", "Woobat", "Bunnelby"],
    "Uncommon": ["Geodude", "Makuhita", "Nosepass", "Noibat", "Rockruff", "Wimpod"],
    "Rare": ["Onix", "Ferroseed", "Carbink", "Nacli", "Glimmet"],
    "Super Rare": ["Shuckle"],
    "Ultra Rare": ["Uxie"],
    "Boss": ["Parasect", "Onix", "Crobat", "Ursaring", "Exploud", "Probopass", "Gigalith", "Swoobat", "Diggersby", "Noivern", "Golisopod"],
    "Boss Rare": ["Shuckle", "Ferrothorn", "Lycanroc", "Glimmora"],
    "Boss Super Rare": ["Uxie"],
    "Boss Ultra Rare": ["Terapagos"]
  },
  "Construction Site": {
    "Common": ["Diglett", "Machop", "Grimer", "Phanpy", "Makuhita", "Nosepass", "Timburr"],
    "Uncommon": ["Magnemite", "Koffing", "Rhyhorn", "Drilbur", "Scraggy", "Alolan Geodude"],
    "Rare": ["Onix", "Tyrogue", "Galarian Meowth"],
    "Super Rare": ["Ditto", "Duraludon"],
    "Ultra Rare": ["Cobalion", "Stakataka"],
    "Boss": ["Machamp", "Magnezone", "Probopass", "Conkeldurr", "Alolan Golem"],
    "Boss Rare": ["Perrserker", "Archaludon"],
    "Boss Super Rare": ["Cobalion", "Stakataka"]
  },
  "Desert": {
    "Common": ["Sandshrew", "Trapinch", "Cacnea", "Skorupi", "Helioptile", "Silicobra", "Bramblin", "Rellor"],
    "Uncommon": ["Gligar", "Numel", "Hippopotas", "Sandile", "Maractus", "Yamask", "Orthworm"],
    "Rare": ["Doduo", "Darumaka", "Sigilyph", "Stonjourner"],
    "Super Rare": ["Lileep", "Anorith", "Gible"],
    "Ultra Rare": ["Regirock", "Tapu Bulu", "Pheromosa"],
    "Boss": ["Sandslash", "Flygon", "Cacturne", "Hippowdon", "Drapion", "Gliscor", "Krookodile", "Darmanitan", "Maractus", "Cofagrigus", "Heliolisk", "Sandaconda", "Brambleghast"],
    "Boss Rare": ["Dodrio", "Cradily", "Armaldo", "Garchomp", "Sigilyph", "Stonjourner"],
    "Boss Super Rare": ["Regirock", "Tapu Bulu", "Pheromosa"]
  },
  "Dojo": {
    "Common": ["Mankey", "Makuhita", "Meditite", "Stufful", "Clobbopus"],
    "Uncommon": ["Croagunk", "Scraggy", "Mienfoo"],
    "Rare": ["Hitmonlee", "Hitmonchan", "Lucario", "Throh", "Sawk", "Pancham"],
    "Super Rare": ["Hitmontop", "Gallade", "Galarian Farfetch'd"],
    "Ultra Rare": ["Terrakion", "Kubfu", "Galarian Zapdos"],
    "Boss": ["Hitmonlee", "Hitmonchan", "Hariyama", "Medicham", "Lucario", "Toxicroak", "Throh", "Sawk", "Scrafty", "Mienshao", "Bewear", "Grapploct", "Annihilape"],
    "Boss Rare": ["Hitmontop", "Gallade", "Pangoro", "Sirfetch'd", "Hisuian Decidueye"],
    "Boss Super Rare": ["Terrakion", "Kubfu", "Galarian Zapdos"],
    "Boss Ultra Rare": ["Zamazenta"]
  },
  "Factory": {
    "Common": ["Machop", "Voltorb", "Bronzor", "Timburr", "Klink"],
    "Uncommon": ["Magnemite", "Elekid", "Magby", "Klefki"],
    "Rare": ["Porygon", "Porygon2"],
    "Super Rare": ["Beldum", "Metang", "Metagross"],
    "Ultra Rare": ["Genesect", "Magearna"],
    "Boss": ["Bronzong", "Electivire", "Magmortar", "Klinklang", "Klefki"],
    "Boss Rare": ["Metagross"],
    "Boss Super Rare": ["Genesect", "Magearna"]
  },
  "Fairy Cave": {
    "Common": ["Jigglypuff", "Marill", "Mawile", "Spritzee", "Swirlix", "Cutiefly", "Morelull", "Milcery"],
    "Uncommon": ["Clefairy", "Togetic", "Ralts", "Carbink", "Comfey", "Hatenna"],
    "Rare": ["Audino"],
    "Super Rare": ["Eternal Floette"],
    "Ultra Rare": ["Diancie", "Enamorus"],
    "Boss": ["Wigglytuff", "Mawile", "Togekiss", "Audino", "Aromatisse", "Slurpuff", "Carbink", "Ribombee", "Shiinotic", "Comfey", "Hatterene", "Alcremie"],
    "Boss Rare": ["Eternal Floette"],
    "Boss Super Rare": ["Diancie", "Enamorus"],
    "Boss Ultra Rare": ["Xerneas"]
  },
  "Forest": {
    "Common": ["Butterfree", "Beedrill", "Venonat", "Bellsprout", "Spinarak", "Pineco", "Beautifly", "Dustox", "Seedot", "Shroomish", "Combee", "Venipede", "Petilil", "Deerling", "Vivillon", "Tarountula", "Nymble", "Shroodle"],
    "Uncommon": ["Ekans", "Hoothoot", "Teddiursa", "Roselia", "Burmy", "Mothim", "Pansage", "Sewaddle", "Rockruff", "Dottler"],
    "Rare": ["Exeggcute", "Scyther", "Heracross", "Stantler", "Treecko", "Tropius", "Karrablast", "Shelmet", "Chespin", "Rowlet", "Squawkabilly", "Toedscool"],
    "Super Rare": ["Durant", "Bloodmoon Ursaluna"],
    "Ultra Rare": ["Kartana", "Wo-Chien"],
    "Boss": ["Venomoth", "Victreebel", "Noctowl", "Ariados", "Forretress", "Beautifly", "Dustox", "Shiftry", "Breloom", "Wormadam", "Mothim", "Vespiquen", "Simisage", "Scolipede", "Lilligant", "Sawsbuck", "Orbeetle", "Spidops", "Lokix", "Grafaiai"],
    "Boss Rare": ["Heracross", "Stantler", "Sceptile", "Escavalier", "Accelgor", "Durant", "Chesnaught", "Decidueye", "Lycanroc", "Toedscruel", "Bloodmoon Ursaluna"],
    "Boss Super Rare": ["Kartana", "Wo-Chien"],
    "Boss Ultra Rare": ["Calyrex"]
  },
  "Grassy Field": {
    "Common": ["Hoppip", "Silcoon", "Cascoon", "Shroomish", "Venipede", "Cottonee", "Petilil"],
    "Uncommon": ["Sunkern", "Miltank", "Seedot", "Combee", "Cherubi", "Foongus"],
    "Rare": ["Bulbasaur", "Growlithe", "Turtwig", "Bonsly", "Noibat"],
    "Ultra Rare": ["Virizion"],
    "Boss": ["Jumpluff", "Miltank", "Vespiquen", "Scolipede", "Whimsicott", "Lilligant", "Noivern"],
    "Boss Rare": ["Venusaur", "Arcanine", "Sudowoodo", "Torterra"],
    "Boss Super Rare": ["Virizion"]
  },
  "Graveyard": {
    "Common": ["Gastly", "Shuppet", "Duskull", "Drifloon", "Litwick", "Phantump", "Pumpkaboo", "Greavard"],
    "Uncommon": ["Cubone", "Yamask", "Sinistea"],
    "Rare": ["Misdreavus", "Mimikyu", "Fuecoco", "Ceruledge"],
    "Super Rare": ["Spiritomb"],
    "Ultra Rare": ["Marshadow", "Spectrier"],
    "Boss": ["Gengar", "Marowak", "Banette", "Drifblim", "Mismagius", "Dusknoir", "Chandelure", "Trevenant", "Gourgeist", "Mimikyu", "Polteageist", "Houndstone"],
    "Boss Rare": ["Skeledirge", "Ceruledge", "Hisuian Typhlosion"],
    "Boss Super Rare": ["Marshadow", "Spectrier"],
    "Boss Ultra Rare": ["Giratina"]
  },
  "Ice Cave": {
    "Common": ["Seel", "Swinub", "Snover", "Snorunt", "Vanillite", "Cubchoo", "Bergmite", "Crabrawler", "Snom"],
    "Uncommon": ["Slowking", "Sneasel", "Smoochum", "Spheal", "Eiscue", "Cetoddle"],
    "Rare": ["Lapras", "Delibird", "Cryogonal"],
    "Super Rare": ["Amaura"],
    "Ultra Rare": ["Articuno", "Regice"],
    "Boss": ["Dewgong", "Glalie", "Walrein", "Weavile", "Mamoswine", "Froslass", "Vanilluxe", "Beartic", "Cryogonal", "Avalugg", "Crabominable", "Cetitan"],
    "Boss Rare": ["Jynx", "Lapras", "Glaceon", "Aurorus"],
    "Boss Super Rare": ["Articuno", "Regice"],
    "Boss Ultra Rare": ["Kyurem"]
  },
  "Island": {
    "Common": ["Oricorio", "Alolan Rattata", "Alolan Sandshrew", "Alolan Vulpix", "Alolan Diglett", "Alolan Meowth", "Alolan Geodude", "Alolan Grimer"],
    "Uncommon": ["Bruxish", "Alolan Raichu", "Alolan Exeggutor", "Alolan Marowak"],
    "Ultra Rare": ["Blacephalon"],
    "Boss": ["Oricorio", "Bruxish", "Alolan Raticate", "Alolan Raichu", "Alolan Sandslash", "Alolan Ninetales", "Alolan Dugtrio", "Alolan Persian", "Alolan Golem", "Alolan Muk", "Alolan Exeggutor", "Alolan Marowak"],
    "Boss Super Rare": ["Blacephalon"]
  },
  "Jungle": {
    "Common": ["Spinarak", "Aipom", "Shroomish", "Vespiquen", "Cherubi", "Purrloin", "Blitzle", "Sewaddle", "Foongus", "Pikipek"],
    "Uncommon": ["Exeggcute", "Tangela", "Tropius", "Combee", "Pansage", "Pansear", "Panpour", "Joltik", "Litleo", "Pancham", "Fomantis", "Komala", "Falinks"],
    "Rare": ["Scyther", "Yanma", "Slakoth", "Seviper", "Carnivine", "Snivy", "Foongus", "Oranguru", "Passimian", "Grookey", "Galarian Ponyta"],
    "Super Rare": ["Kangaskhan", "Chatot", "Kleavor"],
    "Ultra Rare": ["Tapu Lele", "Buzzwole", "Zarude", "Munkidori"],
    "Boss": ["Exeggutor", "Breloom", "Seviper", "Tropius", "Cherrim", "Ambipom", "Carnivine", "Tangrowth", "Yanmega", "Leavanny", "Amoonguss", "Galvantula", "Pyroar", "Pangoro", "Toucannon", "Lurantis", "Komala", "Falinks"],
    "Boss Rare": ["Kangaskhan", "Scizor", "Slaking", "Leafeon", "Serperior", "Amoonguss", "Rillaboom", "Kleavor", "Galarian Rapidash"],
    "Boss Super Rare": ["Tapu Lele", "Buzzwole", "Zarude", "Munkidori"]
  },
  "Laboratory": {
    "Common": ["Grimer", "Voltorb", "Bronzor", "Munna", "Klink"],
    "Uncommon": ["Magnemite", "Solosis", "Klefki"],
    "Rare": ["Ditto", "Porygon", "Rotom"],
    "Ultra Rare": ["Type: Null"],
    "Boss": ["Muk", "Electrode", "Bronzong", "Magnezone", "Reuniclus", "Klinklang"],
    "Boss Rare": ["Porygon-Z", "Rotom"],
    "Boss Super Rare": ["Zygarde", "Type: Null"],
    "Boss Ultra Rare": ["Mewtwo", "Miraidon"]
  },
  "Lake": {
    "Common": ["Psyduck", "Goldeen", "Marill", "Wooper", "Lotad", "Surskit", "Ducklett", "Chewtle"],
    "Uncommon": ["Slowpoke", "Magikarp", "Wishiwashi", "Dewpider", "Flamigo"],
    "Rare": ["Squirtle", "Oshawott", "Froakie", "Sobble"],
    "Super Rare": ["Vaporeon", "Slowking"],
    "Ultra Rare": ["Suicune", "Mesprit"],
    "Boss": ["Golduck", "Slowbro", "Seaking", "Azumarill", "Masquerain", "Swanna", "Wishiwashi", "Araquanid", "Drednaw"],
    "Boss Rare": ["Blastoise", "Gyarados", "Vaporeon", "Slowking", "Samurott", "Greninja", "Inteleon"]
  },
  "Meadow": {
    "Common": ["Ledyba", "Roselia", "Blitzle", "Cottonee", "Minccino", "Flabébé", "Cutiefly", "Gossifleur", "Wooloo"],
    "Uncommon": ["Jigglypuff", "Ponyta", "Mareep", "Snubbull", "Ralts", "Skitty", "Glameow", "Bouffalant", "Oricorio", "Smoliv"],
    "Rare": ["Tauros", "Eevee", "Miltank", "Volbeat", "Illumise", "Spinda", "Applin", "Sprigatito"],
    "Super Rare": ["Chansey", "Sylveon"],
    "Ultra Rare": ["Meloetta"],
    "Boss": ["Tauros", "Ledian", "Granbull", "Miltank", "Gardevoir", "Delcatty", "Roserade", "Purugly", "Zebstrika", "Cinccino", "Bouffalant", "Florges", "Ribombee", "Dubwool", "Arboliva"],
    "Boss Rare": ["Blissey", "Sylveon", "Flapple", "Appletun", "Meowscarada", "Hydrapple", "Hisuian Lilligant"],
    "Boss Super Rare": ["Meloetta"],
    "Boss Ultra Rare": ["Shaymin"]
  },
  "Metropolis": {
    "Common": ["Rattata", "Raticate", "Houndour", "Houndoom", "Zigzagoon", "Linoone", "Patrat", "Watchog", "Lillipup", "Herdier", "Stoutland", "Yamper", "Boltund"],
    "Uncommon": ["Pikachu", "Glameow", "Purugly", "Patrat", "Watchog", "Furfrou", "Espurr", "Meowstic", "Indeedee", "Fidough", "Dachsbun", "Squawkabilly"],
    "Rare": ["Morpeko", "Tandemaus", "Maushold", "Varoom", "Revavroom", "Castform"],
    "Super Rare": ["Ditto", "Eevee", "Smeargle"],
    "Boss": ["Stoutland", "Furfrou", "Meowstic", "Boltund", "Dachsbun"],
    "Boss Rare": ["Maushold", "Revavroom"]
  },
  "Mountain": {
    "Common": ["Pidgey", "Pidgeotto", "Pidgeot", "Spearow", "Fearow", "Rhyhorn", "Rhydon", "Taillow", "Swellow", "Aron", "Lairon", "Aggron", "Swablu", "Altaria", "Starly", "Staravia", "Staraptor", "Pidove", "Tranquill", "Unfezant", "Roggenrola", "Boldore", "Fletchling", "Fletchinder", "Talonflame", "Skiddo", "Gogoat"],
    "Uncommon": ["Machop", "Machoke", "Geodude", "Graveler", "Rhyhorn", "Rhydon", "Natu", "Xatu", "Slugma", "Magcargo", "Aron", "Lairon", "Aggron", "Roggenrola", "Boldore", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Rookidee", "Corvisquire", "Corviknight", "Nacli", "Naclstack", "Garganacl", "Flittle", "Espathra", "Bombirdier"],
    "Rare": ["Murkrow", "Skarmory", "Torchic", "Combusken", "Blaziken", "Spoink", "Grumpig", "Hawlucha", "Klawf"],
    "Super Rare": ["Larvitar", "Pupitar", "Cranidos", "Rampardos", "Shieldon", "Bastiodon", "Gible", "Gabite", "Garchomp", "Rotom", "Archeops", "Axew", "Fraxure"],
    "Ultra Rare": ["Tornadus", "Ting-Lu", "Ogerpon"],
    "Boss": ["Pidgeot", "Fearow", "Skarmory", "Swellow", "Aggron", "Altaria", "Staraptor", "Unfezant", "Braviary", "Mandibuzz", "Talonflame", "Gogoat", "Corviknight", "Garganacl", "Espathra"],
    "Boss Rare": ["Blaziken", "Rampardos", "Bastiodon", "Hawlucha", "Braviary"],
    "Boss Super Rare": ["Rotom", "Tornadus", "Ting-Lu", "Ogerpon"],
    "Boss Ultra Rare": ["Ho-Oh"]
  },
  "Plains": {
    "Common": ["Zubat", "Golbat", "Meowth", "Persian", "Sentret", "Furret", "Poochyena", "Mightyena", "Zigzagoon", "Linoone", "Bidoof", "Bibarel", "Yungoos", "Gumshoos", "Skwovet", "Greedent", "Lechonk", "Oinkologne"],
    "Uncommon": ["Pidgey", "Pidgeotto", "Pidgeot", "Spearow", "Fearow", "Pikachu", "Mankey", "Primeape", "Doduo", "Dodrio", "Poochyena", "Mightyena", "Starly", "Staravia", "Staraptor", "Pidove", "Tranquill", "Unfezant", "Fletchling", "Fletchinder", "Talonflame", "Rockruff", "Lycanroc", "Pawmi", "Pawmo", "Pawmot", "Annihilape"],
    "Rare": ["Abra", "Kadabra", "Shinx", "Luxio", "Luxray", "Buneary", "Lopunny", "Rookidee", "Corvisquire", "Corviknight", "Paldean Tauros"],
    "Super Rare": ["Farfetch'd", "Lickitung", "Chansey", "Eevee", "Snorlax", "Dunsparce", "Dudunsparce"],
    "Ultra Rare": ["Ditto", "Latias", "Latios"],
    "Boss": ["Persian", "Dodrio", "Furret", "Mightyena", "Linoone", "Bibarel", "Lopunny", "Gumshoos", "Greedent", "Oinkologne"],
    "Boss Rare": ["Farfetch'd", "Snorlax", "Lickilicky", "Lycanroc", "Pawmot", "Dudunsparce", "Paldean Tauros"],
    "Boss Super Rare": ["Latias", "Latios"]
  },
  "Power Plant": {
    "Common": ["Pikachu", "Magnemite", "Magneton", "Voltorb", "Electrode", "Electrike", "Manectric", "Shinx", "Luxio", "Luxray", "Dedenne", "Grubbin", "Charjabug", "Pawmi", "Pawmo", "Pawmot", "Tadbulb", "Bellibolt"],
    "Uncommon": ["Electabuzz", "Plusle", "Minun", "Pachirisu", "Emolga", "Togedemaru"],
    "Rare": ["Mareep", "Flaaffy"],
    "Super Rare": ["Jolteon", "Hisuian Voltorb"],
    "Ultra Rare": ["Raikou", "Thundurus", "Xurkitree", "Zeraora", "Regieleki"],
    "Boss": ["Raichu", "Manectric", "Luxray", "Magnezone", "Electivire", "Dedenne", "Vikavolt", "Togedemaru", "Pawmot", "Bellibolt"],
    "Boss Rare": ["Jolteon", "Ampharos", "Hisuian Electrode"],
    "Boss Super Rare": ["Zapdos", "Raikou", "Thundurus", "Xurkitree", "Zeraora", "Regieleki"],
    "Boss Ultra Rare": ["Zekrom"]
  },
  "Sea": {
    "Common": ["Tentacool", "Slowpoke", "Wingull", "Wailmer", "Finneon", "Inkay", "Cramorant", "Finizen"],
    "Uncommon": ["Poliwag", "Slowpoke", "Shellder", "Horsea", "Goldeen", "Staryu", "Magikarp", "Chinchou", "Carvanha", "Buizel", "Panpour", "Wattrel"],
    "Rare": ["Lapras", "Piplup", "Popplio"],
    "Super Rare": ["Kingdra", "Tirtouga"],
    "Boss": ["Tentacruel", "Pelipper", "Sharpedo", "Floatzel", "Lumineon", "Simipour", "Malamar", "Cramorant", "Kilowattrel", "Palafin"],
    "Boss Rare": ["Gyarados", "Kingdra", "Empoleon", "Primarina"],
    "Boss Ultra Rare": ["Lugia"]
  },
  "Seabed": {
    "Common": ["Chinchou", "Remoraid", "Clamperl", "Basculin", "Frillish", "Arrokuda", "Veluza"],
    "Uncommon": ["Tentacool", "Shellder", "Wailmer", "Luvdisc", "Shellos", "Skrelp", "Pincurchin", "Dondozo"],
    "Rare": ["Qwilfish", "Corsola", "Octillery", "Feebas", "Mantyke", "Alomomola", "Tynamo", "Dhelmise"],
    "Super Rare": ["Omanyte", "Kabuto", "Relicanth", "Pyukumuku", "Arctovish", "Galarian Corsola", "Hisuian Qwilfish"],
    "Ultra Rare": ["Nihilego"],
    "Boss": ["Lanturn", "Qwilfish", "Corsola", "Octillery", "Mantine", "Wailord", "Huntail", "Gorebyss", "Luvdisc", "Jellicent", "Alomomola", "Dragalge", "Barraskewda", "Dondozo"],
    "Boss Rare": ["Omastar", "Kabutops", "Milotic", "Relicanth", "Eelektross", "Pyukumuku", "Dhelmise", "Cursola", "Arctovish", "Basculegion", "Overqwil"],
    "Boss Super Rare": ["Nihilego"],
    "Boss Ultra Rare": ["Kyogre"]
  },
  "Slum": {
    "Common": ["Rattata", "Grimer", "Drowzee", "Koffing", "Murkrow", "Shuppet", "Glameow", "Scraggy", "Trubbish"],
    "Uncommon": ["Houndour", "Wormadam", "Stunky", "Pancham", "Maschiff", "Alolan Rattata", "Galarian Zigzagoon"],
    "Rare": ["Sneasel", "Gothita", "Pawniard", "Toxel", "Squawkabilly", "Varoom"],
    "Ultra Rare": ["Guzzlord"],
    "Boss": ["Muk", "Weezing", "Skuntank", "Scrafty", "Garbodor", "Pangoro", "Obstagoon", "Alolan Raticate"],
    "Boss Rare": ["Weavile", "Toxtricity", "Revavroom", "Galarian Weezing"],
    "Boss Super Rare": ["Guzzlord"]
  },
  "Snowy Forest": {
    "Common": ["Sentret", "Sneasel", "Swinub", "Glalie", "Snover", "Froslass", "Cubchoo", "Snom"],
    "Uncommon": ["Teddiursa", "Stantler", "Skiddo", "Eiscue"],
    "Rare": ["Delibird", "Cryogonal", "Avalugg", "Alolan Sandshrew", "Alolan Vulpix", "Galarian Darumaka"],
    "Super Rare": ["Arctozolt", "Galarian Mr. Mime", "Hisuian Sneasel", "Hisuian Zorua", "Hisuian Avalugg"],
    "Ultra Rare": ["Glastrier", "Chien-Pao", "Galarian Articuno"],
    "Boss": ["Glalie", "Abomasnow", "Weavile", "Mamoswine", "Froslass", "Beartic", "Wyrdeer", "Ursaluna"],
    "Boss Rare": ["Mr. Rime", "Arctozolt", "Sneasler", "Alolan Sandslash", "Alolan Ninetales", "Galarian Darmanitan", "Hisuian Zoroark"],
    "Boss Super Rare": ["Glastrier", "Chien-Pao", "Galarian Articuno"],
    "Boss Ultra Rare": ["Zacian"]
  },
  "Space": {
    "Common": ["Cleffa", "Lunatone", "Solrock", "Bronzor", "Munna", "Minior"],
    "Uncommon": ["Baltoy", "Elgyem"],
    "Rare": ["Staryu", "Sigilyph", "Solosis"],
    "Super Rare": ["Porygon", "Beldum"],
    "Ultra Rare": ["Cosmog", "Celesteela"],
    "Boss": ["Clefable", "Lunatone", "Solrock", "Bronzong", "Musharna", "Reuniclus", "Minior"],
    "Boss Rare": ["Metagross", "Porygon-Z"],
    "Boss Super Rare": ["Celesteela"],
    "Boss Ultra Rare": ["Rayquaza", "Solgaleo", "Lunala", "Necrozma"]
  },
  "Swamp": {
    "Common": ["Ekans", "Poliwag", "Wooper", "Lotad", "Gulpin", "Shellos", "Tympole", "Paldean Wooper"],
    "Uncommon": ["Ekans", "Psyduck", "Barboach", "Skorupi", "Croagunk", "Stunfisk", "Mareanie"],
    "Rare": ["Totodile", "Mudkip"],
    "Super Rare": ["Politoed", "Galarian Slowpoke", "Galarian Stunfisk", "Hisuian Sliggoo"],
    "Ultra Rare": ["Azelf", "Poipole"],
    "Boss": ["Arbok", "Poliwrath", "Quagsire", "Ludicolo", "Swalot", "Whiscash", "Gastrodon", "Seismitoad", "Stunfisk", "Toxapex", "Clodsire"],
    "Boss Rare": ["Feraligatr", "Politoed", "Swampert", "Galarian Slowbro", "Galarian Slowking", "Galarian Stunfisk", "Hisuian Goodra"],
    "Boss Super Rare": ["Azelf", "Poipole"]
  },
  "Tall Grass": {
    "Common": ["Nidoran♀", "Nidoran♂", "Oddish", "Paras", "Spinarak", "Kricketot", "Scatterbug", "Fomantis", "Bounsweet", "Nymble"],
    "Uncommon": ["Vulpix", "Venonat", "Nincada", "Zangoose", "Seviper"],
    "Rare": ["Pinsir", "Chikorita", "Girafarig", "Kecleon", "Tropius", "Audino", "Pawniard"],
    "Super Rare": ["Scyther", "Shedinja"],
    "Ultra Rare": ["Raikou", "Entei"],
    "Boss": ["Nidoqueen", "Nidoking", "Vileplume", "Ariados", "Ninjask", "Zangoose", "Seviper", "Kecleon", "Kricketune", "Lurantis", "Tsareena", "Lokix"],
    "Boss Rare": ["Scyther", "Pinsir", "Meganium", "Bellossom", "Farigiraf", "Kingambit", "Raikou", "Entei"]
  },
  "Temple": {
    "Common": ["Gastly", "Natu", "Duskull", "Yamask", "Golett", "Honedge"],
    "Uncommon": ["Cubone", "Baltoy", "Chingling", "Skorupi", "Litwick"],
    "Rare": ["Gimmighoul"],
    "Ultra Rare": ["Hoopa", "Tapu Koko"],
    "Boss": ["Chimecho", "Cofagrigus", "Golurk", "Aegislash"],
    "Boss Rare": ["Gholdengo"],
    "Boss Super Rare": ["Hoopa", "Tapu Koko"],
    "Boss Ultra Rare": ["Regigigas"]
  },
  "Town": {
    "Common": ["Caterpie", "Weedle", "Pidgey", "Rattata", "Spearow", "Sentret", "Hoothoot", "Ledyba", "Spinarak", "Hoppip", "Sunkern", "Poochyena", "Zigzagoon", "Wurmple", "Silcoon", "Cascoon", "Taillow", "Starly", "Bidoof", "Patrat", "Lillipup", "Purrloin", "Pidove", "Cottonee", "Fletchling", "Scatterbug", "Yungoos", "Skwovet", "Blipbug", "Wooloo", "Lechonk"],
    "Uncommon": ["Ekans", "Nidoran♀", "Nidoran♂", "Oddish", "Paras", "Venonat", "Meowth", "Bellsprout", "Poochyena", "Lotad", "Seedot", "Shroomish", "Whismur", "Skitty", "Kricketot", "Combee", "Cherubi", "Venipede", "Minccino", "Pawmi", "Fidough"],
    "Rare": ["Abra", "Cleffa", "Igglybuff", "Surskit", "Happiny", "Rookidee", "Tandemaus"],
    "Super Rare": ["Eevee", "Pichu", "Togepi", "Ralts", "Nincada", "Riolu"],
    "Ultra Rare": ["Ditto", "Munchlax", "Zorua"]
  },
  "Volcano": {
    "Common": ["Vulpix", "Growlithe", "Ponyta", "Slugma", "Poochyena", "Numel", "Spoink", "Swablu", "Rolycoly"],
    "Uncommon": ["Magmar", "Meditite", "Torkoal", "Pansear", "Heatmor", "Salandit", "Turtonator", "Alolan Diglett"],
    "Rare": ["Charmander", "Cyndaquil", "Chimchar", "Tepig", "Fennekin", "Litten", "Scorbunny", "Charcadet"],
    "Super Rare": ["Flareon", "Larvesta", "Hisuian Growlithe"],
    "Ultra Rare": ["Moltres", "Heatran", "Volcanion", "Chi-Yu"],
    "Boss": ["Ninetales", "Arcanine", "Rapidash", "Magcargo", "Camerupt", "Torkoal", "Magmortar", "Simisear", "Heatmor", "Salazzle", "Turtonator", "Coalossal", "Alolan Diglett"],
    "Boss Rare": ["Charizard", "Flareon", "Typhlosion", "Infernape", "Emboar", "Volcarona", "Delphox", "Incineroar", "Cinderace", "Armarouge", "Hisuian Arcanine"],
    "Boss Super Rare": ["Moltres", "Heatran", "Volcanion", "Chi-Yu"],
    "Boss Ultra Rare": ["Reshiram"]
  },
  "Wasteland": {
    "Common": ["Larvitar", "Vibrava", "Bagon", "Gible", "Axew", "Goomy", "Goodra", "Jangmo-o"],
    "Uncommon": ["Swablu", "Deino", "Drampa", "Cyclizar"],
    "Rare": ["Dratini", "Dreepy", "Frigibax"],
    "Super Rare": ["Aerodactyl", "Druddigon", "Tyrunt", "Dracozolt", "Dracovish"],
    "Ultra Rare": ["Regidrago"],
    "Boss": ["Dragonite", "Tyranitar", "Flygon", "Salamence", "Garchomp", "Haxorus", "Goodra", "Drampa", "Kommo-o", "Dragapult", "Baxcalibur"],
    "Boss Rare": ["Aerodactyl", "Druddigon", "Tyrantrum", "Dracozolt", "Dracovish"],
    "Boss Super Rare": ["Regidrago"],
    "Boss Ultra Rare": ["Dialga"]
  },
}
